### ISSUE TITLE
AoT error

### ISSUE THREAD

**Issue by enricodeleo** [Zefling/ng-walkthrough#7]
The module causes an error during AoT compiling: 

```bash
[23:13:55]  typescript error
            Error encountered resolving symbol values statically. Could not resolve @angular/cdk/portal relative to
            /Users/enrico/Development/app/node_modules/angular-walkthrough/angular-walkthrough.d.ts.,
            resolving symbol WalkthroughModule in
            /Users/enrico/Development/app/node_modules/angular-walkthrough/angular-walkthrough.d.ts,
            resolving symbol WalkthroughModule in
            /Users/enrico/Development/app/node_modules/angular-walkthrough/angular-walkthrough.d.ts

Error: The Angular AoT build failed. See the issues above
    at /Users/enrico/Development/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:237:55
    at step (/Users/enrico/Development/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Users/enrico/Development/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Users/enrico/Development/app/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>
```

**Comment by Zefling** [comment]
What is your version of Angular?

**Comment by enricodeleo** [comment]
Angular 5 (Ionic 3.9.2)

**Comment by Zefling** [comment]
Did you try this?
`npm install --save @angular/cdk`

**Comment by enricodeleo** [comment]
I overlooked that :) It seems to work now. Thanks!

**Comment by Zefling** [comment]
Cool.

Note : angular/cdk is on required points. ;)
